<?php

$announcement_list = array("announcement_1" => array('title' => "2014 Rossignol District Snowboard",
                                                     'category' => "Доски и лыжи",
                                                     'price' => "10999",
                                                     'URL-img' => "/img/lot-1.jpg",
                                                     'id' => "0"),
                           "announcement_2" => array('title'=>"DC Ply Mens 2016/2017 Snowboard",
                                                     'category' => "Доски и лыжи",
                                                     'price' => "159999",
                                                     'URL-img' => "/img/lot-2.jpg",
                                                     'id' => "1"),
                           "announcement_3" => array('title'=>"Крепления Union Contact Pro 2015 года размер L/XL",
                                                     'category' => "Крепления",
                                                     'price' => "8000",
                                                     'URL-img' => "/img/lot-3.jpg",
                                                     'id' => "2"),
                           "announcement_4" => array('title'=>"Ботинки для сноуборда DC Mutiny Charocal",
                                                     'category' => "Ботинки",
                                                     'price' => "10999",
                                                     'URL-img' => "/img/lot-4.jpg",
                                                     'id' => "3"),
                           "announcement_5" => array('title'=>"Куртка для сноуборда DC Mutiny Charocal",
                                                     'category' => "Одежда",
                                                     'price' => "7500",
                                                     'URL-img' => "/img/lot-5.jpg",
                                                     'id' => "4"),
                           "announcement_6" => array('title'=>"Маска Oakley Canopy",
                                                     'category' => "Разное",
                                                     'price' => "5400",
                                                     'URL-img' => "/img/lot-6.jpg",
                                                     'id' => "5")
);

?>